### ISSUE TITLE
Field wxMpService in com.able.tbk.web.api.WXController required a bean of type 'me.chanjar.weixin.mp.api.WxMpService' that could not be found.

### ISSUE THREAD

**Issue by pobc** [Wechat-Group/weixin-java-demo-springmvc#16]
运行报错
Field wxMpService in com.able.tbk.web.api.WXController required a bean of type 'me.chanjar.weixin.mp.api.WxMpService' that could not be found.

**Comment by binarywang** [comment]
明显是你自己改了什么东西

**Comment by binarywang** [comment]
com.able.tbk.web.api. 你这个包名不是demo里的东西，自己对比demo检查下改了什么东西

**Comment by pobc** [comment]
这是jar包里面的，weixin-java-demo-springmvc/src/main/java/com/github/weixin/demo/controller/CoreController.java  第16行 引用了这个类

**Comment by binarywang** [comment]
你是在逗我吗？我说的是`com.able.tbk.web.api. `你这个包名

**Comment by pobc** [comment]
我是在自己的spring boot项目里面引用了 weixin-java-mp的jar包，然后使用自动注入的方式使用 WxMpService，但是报错了。我看到jar包里面的WxMpServiceImpl 类上面没有写 @Service，请问我要怎么配置呢？ 在spring boot项目里面

**Comment by binarywang** [comment]
参考本demo是怎么做的，仿照实现即可，另外建议补充下spring相关基础知识

**Comment by trojansun** [comment]
如果你是用作者的demo的话，不会出现这个问题。如果你用自己写的代码进行测试，出现你这个问题的原因有可能是你的代码中，没有跟作者一样，在WxMpConfiguration中注入bean，所以你会报WxMpService、WxMpMessageRouter相关错误，如果你增加了WxMpConfiguration中的相关注入，就会解决你的这个问题。
